# use C-a instead of C-b, mostly for vi editing
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# use vi style commands
setw -g mode-keys vi

# "theme"
setw -g window-status-current-style 'fg=white bg=red bold'
#setw -g window-status-current-style bright
set -g status-justify centre

# increase history scrollback, default is 2000
set-option -g history-limit 100000

